[build]
  base    = "."
  command = "hugo"
  publish = "public"

[build.environment]
  # match your local Hugo version
  HUGO_VERSION           = "0.147.2"
  # ensure Netlify clones your theme submodule
  GIT_SUBMODULE_STRATEGY = "recursive"
