[build]
  # build from the repo root:
  base    = "."
  command = "hugo"
  publish = "public"

[build.environment]
  # install the same Hugo version you use locally
  HUGO_VERSION = "0.147.2+extended+withdeploy"
